[versions]
junit = "4.13.2"
hamcrestJunit = "2.0.0.0"
mockito = "5.11.0"
supportAnnotation = "1.7.1"
okhttp3Mockwebserver = "3.12.7"
gson = "2.10.1"

gradleNexus = "1.3.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
hamcrestJunit = { group = "org.hamcrest", name = "hamcrest-junit", version.ref = "hamcrestJunit" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
supportAnnotation = { group = "androidx.annotation", name = "annotation", version.ref = "supportAnnotation" }
okhttp3Mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp3Mockwebserver" }
gson  = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
gradle-nexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradleNexus" }
